server:
  port: 8080 

spring:
  cloud:
    gateway:
      routes:
        - id: route-comptes
          uri: lb://COMPTESERVICE 
          predicates:
            - Path=/api/compte/**

        - id: route-clients
          uri: lb://CLIENTSERVICE
          predicates:
            - Path=/api/clients/** 
    service-registry:
      auto-registration:
        register-management: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      prometheus.scrape: "true"
      prometheus.path: "/actuator/prometheus"
      prometheus.port: "${server.port}"
      
management:
  endpoints:
    web:
      exposure:
        include: "*"


