server:
  port: 46001

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_clients 
  cloud: 
    service-registry:
      auto-registration:
        register-management: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      prometheus.scrape: "true"
      prometheus.path: "/actuator/prometheus"
      prometheus.port: "${server.port}"
      

management:
  endpoints:
    web:
      exposure:
        include: "*"



